export const mockData: string[][] = [
    ['стрница 1', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 1', 'element 8', 'element 9', 'element 10', 'страница 2', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 2', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 2', 'element 8', 'element 9', 'element 10', 'element 2', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 3', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 3', 'element 8', 'element 9', 'element 10', 'element 3', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 4', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 4', 'element 8', 'element 9', 'element 10', 'element 4', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 5', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 5', 'element 8', 'element 9', 'element 10', 'element 5', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 6', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 6', 'element 8', 'element 9', 'element 10', 'element 6', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 7', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 7', 'element 8', 'element 9', 'element 10', 'element 7', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 8', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 8', 'element 8', 'element 9', 'element 10', 'element 8', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 9', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 9', 'element 8', 'element 9', 'element 10', 'element 9', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
    ['element 10', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 10', 'element 8', 'element 9', 'element 10', 'element 10', 'element 2', 'element 3', 'element 4', 'element 5', 'element 6', 'element 71', 'element 8', 'element 9', 'element 10'],
]